package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import modelo.DatosConsulta;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class Venta extends javax.swing.JFrame {

	DatosConsulta datos;
    /**
     * Creates new form Venta
     */
    public Venta(DatosConsulta datos) {
    	this.datos = datos;
        initComponents();
        
        idventa.setText("VENTA #"+datos.getidVenta());
        idFuncion.setText("Función: "+datos.getIdFuncion());
        pelicula.setText("Película "+datos.getPelicula());
        fecha.setText("Fecha: "+datos.getFecha());
        sala.setText("Sala: "+datos.getSala());
        tipoSilleteria.setText("Tipo Silleteria: "+datos.getTipoSilleteria());
        numBoletas.setText("Cantidad boletas: "+datos.getCantidadBoletas());
        valorBoleta.setText("Precio Boleta: "+datos.getValorBoleta());
        valor.setText("Valor Total: "+datos.getValorTotalVenta());
        
        this.setTitle("Cineplanet");
        this.setIconImage(new ImageIcon(getClass().getResource("/vista/Img/globe.png")).getImage());
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        numeroVenta = new javax.swing.JPanel();
        idventa = new javax.swing.JLabel();
        tipoSilleteria = new javax.swing.JLabel();
        cantidadBoletas1 = new javax.swing.JLabel();
        cantidadBoletas7 = new javax.swing.JLabel();
        sala = new javax.swing.JLabel();
        idFuncion = new javax.swing.JLabel();
        pelicula = new javax.swing.JLabel();
        valorBoleta = new javax.swing.JLabel();
        precioBoleta = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        numBoletas = new javax.swing.JLabel();
        idventa1 = new javax.swing.JLabel();
        botonGenerarFactura = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idventa.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        idventa.setText("VENTA");

        tipoSilleteria.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tipoSilleteria.setText("Tipo Silleteria: ");

        cantidadBoletas1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        cantidadBoletas7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        sala.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        sala.setText("Sala:");

        idFuncion.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        idFuncion.setText("Función:func");

        pelicula.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        pelicula.setText("Película:");

        valorBoleta.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        valorBoleta.setText("Precio Boleta: ");

        precioBoleta.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        valor.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        valor.setText("Valor Total: vt");

        fecha.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        fecha.setText("Fecha: ");

        numBoletas.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        numBoletas.setText("Cantidad boletas:  ");

        idventa1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        idventa1.setText("_________________________________________");

        botonGenerarFactura.setText("Generar factura");
        botonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numeroVentaLayout = new javax.swing.GroupLayout(numeroVenta);
        numeroVenta.setLayout(numeroVentaLayout);
        numeroVentaLayout.setHorizontalGroup(
            numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numeroVentaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numeroVentaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(numeroVentaLayout.createSequentialGroup()
                                .addComponent(valorBoleta)
                                .addGap(222, 222, 222)
                                .addComponent(botonGenerarFactura))
                            .addComponent(tipoSilleteria, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(numeroVentaLayout.createSequentialGroup()
                                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadBoletas7)
                                .addGap(367, 367, 367)
                                .addComponent(precioBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sala)))
                    .addGroup(numeroVentaLayout.createSequentialGroup()
                        .addComponent(cantidadBoletas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numeroVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(idventa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
            .addGroup(numeroVentaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(idventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        numeroVentaLayout.setVerticalGroup(
            numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numeroVentaLayout.createSequentialGroup()
                .addComponent(idventa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(idventa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numeroVentaLayout.createSequentialGroup()
                        .addComponent(cantidadBoletas1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294)
                        .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(numeroVentaLayout.createSequentialGroup()
                                .addGap(0, 19, Short.MAX_VALUE)
                                .addComponent(precioBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(numeroVentaLayout.createSequentialGroup()
                                .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantidadBoletas7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(numeroVentaLayout.createSequentialGroup()
                        .addComponent(idFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sala, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(numeroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(numeroVentaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoSilleteria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numeroVentaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonGenerarFactura)
                                .addGap(72, 72, 72))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(numeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarFacturaActionPerformed
        try {
			FileWriter archivo = new FileWriter("/facturas/factura-venta"+datos.getidVenta());

			archivo.write("========================= Cineplanet =================== \n\n");
			archivo.write("FACTURA VENTA #"+datos.getidVenta()+"\n\n");
			archivo.write("Función: "+datos.getIdFuncion()+"\n\n");
			archivo.write("Película: "+datos.getPelicula()+"\n\n");
			archivo.write("Fecha: "+ datos.getFecha()+"\n\n");
			archivo.write("Sala: "+ datos.getSala()+"\n\n");
			archivo.write("Tipo Silleteria: "+ datos.getTipoSilleteria()+"\n\n");
			archivo.write("Cantidad de boletas: "+ datos.getCantidadBoletas()+"\n\n");
			archivo.write("Precio boleta: " + datos.getValorBoleta()+"\n\n");
			archivo.write("Valor total: "+ datos.getValorTotalVenta()+"\n\n");
			archivo.write("============== ¡Muchas gracias por su compra! =============\n\n");		
		
			archivo.close();
			JOptionPane.showMessageDialog(null, "Se ha generado la factura.");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_botonGenerarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Venta().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarFactura;
    private javax.swing.JLabel cantidadBoletas1;
    private javax.swing.JLabel cantidadBoletas7;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel idFuncion;
    private javax.swing.JLabel idventa;
    private javax.swing.JLabel idventa1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel numBoletas;
    private javax.swing.JPanel numeroVenta;
    private javax.swing.JLabel pelicula;
    private javax.swing.JLabel precioBoleta;
    private javax.swing.JLabel sala;
    private javax.swing.JLabel tipoSilleteria;
    private javax.swing.JLabel valor;
    private javax.swing.JLabel valorBoleta;
    // End of variables declaration//GEN-END:variables
}
